import { BookingItem } from "@pages/MyBooking/context";

export const mockBookings: BookingItem[] = [
    {
        id: "B001",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Awaiting Pickup",
        address: "123 Changi, Singapore",
        duration: "6 months (180 days)",
        paymentMode: "ApplePay",
    },
    {
        id: "B002",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Box to be delivered",
        address: "280 Bukit Batok East Avenue 3 #01-327",
        duration: "6 months (180 days)",
        paymentMode: "PAYNOW",
    },
    {
        id: "B003",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Box to be delivered",
        address: "5 Ang Mo Kio Industrial Park 2a 03-33",
        duration: "6 months (180 days)",
    },
    {
        id: "B004",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Box to be delivered",
        address: "123 Changi, Singapore",
        duration: "6 months (180 days)",
    },
    {
        id: "B005",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Stored",
        address: "123 Changi, Singapore",
        duration: "6 months (180 days)",
        paymentMode: "CreditCard",
    },
    {
        id: "B006",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Stored",
        address: "280 Bukit Batok East Avenue 3 #01-327",
        duration: "6 months (180 days)",
        paymentMode: "PAYNOW",
    },
    {
        id: "B007",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Stored",
        address: "280 Bukit Batok East Avenue 3 #01-327",
        duration: "6 months (180 days)",
        paymentMode: "CreditCard",
    },
    {
        id: "B008",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Stored",
        address: "280 Bukit Batok East Avenue 3 #01-327",
        duration: "6 months (180 days)",
        paymentMode: "CreditCard",
    },
    {
        id: "B009",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Returned",
        address: "123 Changi, Singapore",
        duration: "6 months (180 days)",
        paymentMode: "PAYNOW",
    },
    {
        id: "B010",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Cancelled",
        address: "280 Bukit Batok East Avenue 3 #01-327",
        duration: "6 months (180 days)",
        paymentMode: "PAYNOW",
    },
    {
        id: "B011",
        productName: "standard-box",
        quantity: 2,
        startDate: "19 Mar 2025",
        endDate: "19 Sep 2025",
        status: "Cancelled",
        address: "280 Bukit Batok East Avenue 3 #01-327",
        duration: "6 months (180 days)",
        paymentMode: "PAYNOW",
    },
];
